[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mitene_download"
version = "7.0.0"
requires-python = ">=3.11"
dependencies = [
    "aiohttp[speedups]",
    "aiofiles",
    "tqdm",
    "aiosqlite",
    "beautifulsoup4",
    "piexif",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
readme = "README.md"
dynamic = ["description"]

[project.license]
file = "LICENSE"

[project.urls]
Source = "https://github.com/suasive93/mitene_download_2.1"

[[project.authors]]
name = "Jérome Perrin"

[[project.authors]]
name = "Suasive93"

[project.scripts]
mitene_download = "mitene_download:main"
